const pharmacies = [

{name:"Pharmacie El Fath",address:"Nº 29 Lot El Fath 01, Tiznit (face à la mosquée El Fath)",phone:"0528863442"},
{name:"Pharmacie Abouzaid",address:"Route d'Aglou, près de l'Hôpital Hassan I",phone:"0528601500"},
{name:"Pharmacie Souk",address:"Route Tafraoute, Quartier Industriel",phone:"0528860200"},
{name:"Pharmacie Erac",address:"Rue 30, Lotissement Erac",phone:"0528600346"},
{name:"Pharmacie Route de Guelmim",address:"Boulevard Bir Anzarane Route de Guelmim",phone:"0528866778"},
{name:"Pharmacie Al Amal",address:"Avenue 30 Afrag, près du café Venezia",phone:"0528861729"},
{name:"Pharmacie Assafar N Issafarne",address:"Avenue Hassan II N°6 Lot Al Houria",phone:"0528862434"},
{name:"Pharmacie Europe",address:"Amicale des fonctionnaires, en face du parc My Abdellah",phone:"0528863545"},
{name:"Pharmacie des Amicales",address:"En face de la Mosquée Assouna",phone:"0528861550"},
{name:"Pharmacie Charif Idrissi",address:"Hors Bab Aglou, près de la clinique Jassim",phone:"0528602525"},
{name:"Pharmacie Avenue 30",address:"Avenue 30 près du lycée Al Wahda",phone:"0528864433"},
{name:"Pharmacie Afrag",address:"Boulevard Driss El Harti près de la mosquée Al Qods",phone:"0528600788"},
{name:"Pharmacie Ben Omar",address:"Rue Afrag en face BMCE",phone:"0528600814"},
{name:"Pharmacie La Santé",address:"Quartier Al Massira",phone:"0528602526"},
{name:"Pharmacie Ikram",address:"Immeuble Nasr Route Aglou",phone:"0707150651"},
{name:"Pharmacie du Peuple",address:"Près du tribunal rue Allal ben Abdellah",phone:"0528601755"},
{name:"Pharmacie du Sud",address:"Près Amicale des fonctionnaires",phone:"0528601400"},
{name:"Pharmacie Nouvelle",address:"Avenue Sidi Abderrahmane",phone:"0528862742"},
{name:"Pharmacie Nassiri",address:"1 Avenue Mohammed V Youssoufia",phone:"0528600721"},
{name:"Pharmacie Bel Haj",address:"Souk Si Blaid",phone:"0528601782"},
{name:"Pharmacie Attakwine",address:"Route Tafraoute près formation professionnelle",phone:"0525255060"},
{name:"Pharmacie Hay Nakhil",address:"Rue principale Nakhil",phone:"0528861949"},
{name:"Pharmacie La Gare",address:"Route Tafraoute Souk El Khmiss",phone:"0667134940"},
{name:"Pharmacie Iligh",address:"Lot Al Moustakbal Cité Saaidia",phone:"0528860289"},
{name:"Pharmacie Ibn Sina",address:"Route Guelmim face station Shell",phone:"0528860285"},
{name:"Pharmacie La Grande",address:"Avenue Mohammed V Youssoufia",phone:"0528600814"},
{name:"Pharmacie Fouk El Wad",address:"Boulevard Sidi Abderrahmane direction Tarka",phone:"0528601061"},
{name:"Pharmacie Mokhtar Soussi",address:"Face hôpital Houmane El Fatouaki",phone:"0528863565"},
{name:"Pharmacie Chifaa",address:"Ancienne route Aglou près école Assfa",phone:"0707735712"},
{name:"Pharmacie Rahmatallah",address:"Lotissement Nahda 2",phone:"0528866233"},
{name:"Pharmacie Provinciale",address:"Route Agadir",phone:"0528600775"},
{name:"Pharmacie Almostaqbal",address:"Lot Al Oubour Ain Zerka",phone:"0528602111"},
{name:"Pharmacie l'Hôpital",address:"Route Aglou face hôpital Hassan I",phone:"0528863285"},
{name:"Pharmacie El Atlas",address:"Intersection Route Ifni et Rue 30",phone:"0528601534"},
{name:"Pharmacie Sahl Souss",address:"Place El Mechouar",phone:"0528861741"},
{name:"Pharmacie Route Ifni",address:"Route Ifni près station Afriquia",phone:"0528601296"},
{name:"Pharmacie Centrale",address:"Bloc B Amicale des fonctionnaires",phone:"0528861731"},
{name:"Pharmacie Al Mers",address:"Rue El Mers face dispensaire",phone:"0528860728"}

];
const pharmacies = [

{name:"صيدلية الفتح",address:"أمام مسجد الفتح"},
{name:"صيدلية أبوزيد",address:"طريق أكلو، بالقرب من مستشفى الحسن الأول"},
{name:"صيدلية السوق",address:"طريق تفراوت، الحي الصناعي"},
{name:"صيدلية إراك",address:"شارع 30، تجزئة إراك، تيزنيت"},
{name:"صيدلية طريق كلميم",address:"شارع بئر أنزاران، طريق كلميم"},
{name:"صيدلية الأمل",address:"شارع 30 أفراك، بالقرب من مقهى فينيسيا"},
{name:"صيدلية أسفار ن إسفارن",address:"رقم 6 شارع الحسن الثاني، تجزئة الحرية"},
{name:"صيدلية أوروبا",address:"ودادية الموظفين، امام حديقة مولاي عبد الله"},
{name:"صيدلية الوداديات",address:"امام مسجد السنة"},
{name:"صيدلية الشريف الإدريسي",address:"خارج باب أكلو، بالقرب من عيادة جاسم"},
{name:"صيدلية شارع 30",address:"شارع 30، بالقرب من ثانوية الوحدة"},
{name:"صيدلية أفراك",address:"شارع دريس الحارتي، بالقرب من مسجد القدس"},
{name:"صيدلية بن عمر",address:"شارع 30 أفراك، مقابل BMCE"},
{name:"صيدلية الصحة",address:"حي المسيرة، بين حمام أسكتي وشارع الوفاق"},
{name:"صيدلية إكرام",address:"عمارة نصر، طريق أكلو"},
{name:"صيدلية الشعب",address:"بالقرب من المحكمة الابتدائية، شارع علال بن عبد الله"},
{name:"صيدلية الجنوب",address:"بالقرب من جمعية الموظفين"},
{name:"صيدلية الجديدة",address:"شارع سيدي عبد الرحمان"},
{name:"صيدلية نصيري",address:"رقم 1 شارع محمد الخامس، اليوسفية"},
{name:"صيدلية بلحاج",address:"سوق سي بلعيد"},
{name:"صيدلية التكوين",address:"طريق تفراوت، قرب التكوين المهني"},
{name:"صيدلية حي النخيل",address:"الشارع الرئيسي النخيل، تجزئة النخيل"},
{name:"صيدلية المحطة",address:"طريق تفراوت، بالقرب من السوق الأسبوعي"},
{name:"صيدلية طريق كلميم",address:"23 شارع بئر أنزاران، طريق كلميم"},
{name:"صيدلية إيليغ",address:"السعيدية، بالقرب من مدرسة يعقوبي"},
{name:"صيدلية ابن سينا",address:"طريق كلميم، امام محطة الوقود شيل"},
{name:"صيدلية الكبرى",address:"شارع محمد الخامس، اليوسفية"},
{name:"صيدلية فوق الواد",address:"اتجاه تاركا، شارع سيدي عبد الرحمان"},
{name:"صيدلية المختار السوسي",address:"امام مستشفى حمان الفتوكي"},
{name:"صيدلية الشفاء",address:"الطريق القديم لأكلو، بالقرب من مدرسة الصفا"},
{name:"صيدلية رحمة الله",address:"تجزئة نهضة 2، أمام مؤسسة رواد النهضة"},
{name:"الصيدلية الإقليمية",address:"طريق أكادير"},
{name:"صيدلية المستقبل",address:"تجزئة العبور، العين الزرقة"},
{name:"صيدلية المستشفى",address:"طريق أكلو، امام مستشفى الحسن الأول"},
{name:"صيدلية الأطلس",address:"تقاطع طريق إفني وشارع 30"},
{name:"صيدلية سهل سوس",address:"ساحة المشوار"},
{name:"صيدلية طريق إفني",address:"طريق إفني، بالقرب من محطة أفريقيا"},
{name:"الصيدلية المركزية",address:"رقم 186 بلوك B، جمعية الموظفين"},
{name:"صيدلية المرس",address:"شارع المرس، امام المركز الصحي"}

];const pharmacies = [
